# Generated by Django 5.2.9 on 2026-02-10 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_teammember"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="teammember",
            options={
                "ordering": ["department", "division", "order", "last_name"],
                "verbose_name": "Membre de l'équipe",
                "verbose_name_plural": "Membres de l'équipe",
            },
        ),
        migrations.AddField(
            model_name="teammember",
            name="division",
            field=models.CharField(
                blank=True,
                choices=[
                    ("rh_comm", "Ressource Humaine, Communication, Marketing"),
                    ("comptable", "Comptable et Développement"),
                    ("beton", "Béton"),
                    (
                        "environnement",
                        "Environnement, Hydrogéologie, Pédologie, Bitume",
                    ),
                    ("geotechnique", "Géotechnique Routière et Bâtiment"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="teammember",
            name="department",
            field=models.CharField(
                choices=[
                    ("direction", "Direction Générale"),
                    ("recherche", "Recherche, Innovation, Qualité"),
                    ("admin", "Administratif"),
                    ("etudes", "Études, Maîtrise d'Oeuvre, Contrôles Extérieurs"),
                    ("laboratoire", "Laboratoire"),
                ],
                max_length=20,
            ),
        ),
    ]
